apiVersion: v2
name: cilium
description: Cilium Helm chart
type: application
version: 1.0.0
appVersion: "1.16.3"

dependencies:
- name: cilium
  version: 1.16.3
  repository: https://helm.cilium.io/
  alias: cilium

