cilium:
  kubeProxyReplacement: true
  k8sServiceHost:
  k8sServicePort: 6443

  ipam:
    operator:
      mode: "kubernetes"
      clusterPoolIPv4PodCIDRList: 10.42.0.0/16
  ipv4NativeRoutingCIDR: 10.42.0.0/16
  ipv4:
    enabled: true

  hostServices:
    enabled: true

  bpf:
    masquerade: true
    nativeRoutingCIDR: "10.42.0.0/16"

  # loadBalancer:
  #   mode: "dsr"
  operator:
    replicas: 1

  dnsProxy:
    enabled: true
    domain: "cluster.local"

  security:
    enableHostFirewall: true
    enableEncryption: true

  etcd:
    enabled: false

  clusterwide:
    enabled: true
