cilium:
  kubeProxyReplacement: true
  k8sServiceHost: 127.0.0.1 #Single node
  k8sServicePort: 6443
  sessionAffinity: true

  ipam:
    mode: "kubernetes"
    operator:
      clusterPoolIPv4PodCIDRList: 10.42.0.0/16
  ipv4NativeRoutingCIDR: "10.42.0.0/16"
  ipv4:
    enabled: true
  ipv6:
    enabled: false

  enableIPMasqAgent: false
  enableIPv4Masquerade: true
  bpf:
    masquerade: true

  routingMode: "native" #Single node
  autoDirectNodeRoutes: true #Single node

  loadBalancer:
    algorithm: "maglev"
    mode: "snat" #Single node

  hostServices:
    enabled: true
  bandwidthManager:
    enabled: true

  nodeinit:
    enabled: true
  operator:
    replicas: 1 #Single node
