cilium:
  kubeProxyReplacement: true
  k8sServiceHost:
  k8sServicePort: 6443
  sessionAffinity: true

  ipam:
    mode: "cluster-pool"
    operator:
      clusterPoolIPv4PodCIDRList: 10.250.0.0/16
  ipv4:
    enabled: true
  ipv6:
    enabled: false

  autoDirectNodeRoutes: false
  enableIPMasqAgent: false
  enableIPv4Masquerade: true
  bpf:
    masquerade: true

  loadBalancer:
    algorithm: "maglev"
    mode: "snat"
    acceleration: "native"
  ipv4NativeRoutingCIDR: "10.250.0.0/16"

  hostServices:
    enabled: true
  bandwidthManager:
    enabled: true

  nodeinit:
    enabled: true
    reconfigureKubelet: true
    removeCbrBridge: true

  encryption:
    enabled: true
    type: "ipsec"

  envoy:
    enabled: false
