cilium:
  kubeProxyReplacement: true
  k8sServiceHost:
  k8sServicePort: 6443
  sessionAffinity: true

  ipam:
    mode: "cluster-pool"
    operator:
      clusterPoolIPv4PodCIDRList: 10.255.0.0/16
  bpf:
    masquerade: true
  ipv4NativeRoutingCIDR: "10.255.0.0/16"

  encryption:
    enabled: true
    type: "wireguard"

  envoy:
    enabled: false
