{{- if .Values.clusterIssuer.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuer.metadata.name }}
spec:
  acme:
    email: {{ .Values.clusterIssuer.email }}
    server: {{ .Value.clusterIssuer.server }}
    privateKeySecretRef:
      name: {{ .Values.clusterIssuer.privateKeySecretRef.name }}
    solvers:
    - http01:
        ingress:
          ingressClassName: {{ .Values.clusterIssuer.ingressClassName }}
{{- end }}
