# # Kubernets
# secretStore:
#   clusterWide: true
#   provider:
#     type: kubernetes
#     kubernetes:
#       auth:
#         serviceAccount:
#           create: true
#           name: "todo-secret-store-sa"
#   labels:
#     environment: prod
#   annotations:
#     description: "Kubernetes secrets store"

# nameOverride: ""
# fullnameOverride: ""
#
# secretStore:
#   clusterWide: true
#   provider:
#     type: kubernetes
#     kubernetes:
#       remoteNamespace: default # Source namespace if not clusterIssuer
#        # Optional: restrict access to specific namespaces if cluster wide true
#       # List of allowed namespaces (only used when clusterWide: true)
#       allowedNamespaces:
#         - portfolio
#         - todo-go-htmx
#         - workinghours
#       # List of allowed secret names
#       allowedSecrets:
#         - portfolio-secret
#         - todo-go-htmx-secret
#         - workinghours-secret
#       auth:
#         serviceAccount:
#           create: true
#           name: "my-secret-store-sa"
#           annotations: {}  # Specific annotations for ServiceAccount
#   labels:
#     environment: prod
#   annotations:
#     description: "Kubernetes secrets store"
#
# Vault
# secretStore:
#   provider:
#     type: vault
#     vault:
#       server: "https://vault.example.com:8200"
#       path: "secret/data"
#       auth:
#         secretName: vault-token-secret
#   labels:
#     environment: prod
#     type: vault
#   annotations:
#     description: "HashiCorp Vault store"

## AWS
# secretStore:
#   provider:
#     type: aws
#     aws:
#       region: us-west-2
#       auth:
#         secretName: aws-secret-creds  # Secret containing AWS credentials
#   labels:
#     environment: prod
#     cloud: aws
#   annotations:
#     description: "AWS Secrets Manager store"
