apiVersion: v2
name: minio-tenant
description: Minio Tenant Helm chart configurated by Ujstor
type: application
version: 1.0.0
appVersion: "v6.0.4"

dependencies:
- name: tenant
  version: 6.0.4
  repository: https://operator.min.io
  alias: minio-tenant
