minio-tenant:
  tenant:
    name: minio
    configuration:
      name: minio-admin-secret
    pools:
      - servers: 1
        name: pool-0
        volumesPerServer: 1
        size: 10Gi
    buckets: []
      # - name: test-bucket
      #   objectLock: false
      #   region: us-east-1
  ingress:
    api:
      enabled: false
      ingressClassName: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        nginx.ingress.kubernetes.io/proxy-body-size: "2048m"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "1200"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "1200"
      tls: 
        - secretName: minio-api-tls
          hosts:
            - minio.domain.com
      host: minio.domain.com
      path: /
      pathType: Prefix
    console:
      enabled: false
      ingressClassName: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        nginx.ingress.kubernetes.io/proxy-body-size: "2048m"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "1200"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "1200"
      tls: 
        - secretName: minio-console-tls
          hosts:
            - minio-console.domain.com
      host: minio-console.domain.com
      path: /
      pathType: Prefix

secret-store:
  secretStore:
    clusterWide: false
    provider:
      type: kubernetes
      kubernetes:
        auth:
          serviceAccount:
            create: true
            name: "minio-secret-store-sa"
