minio-tenant:
  tenant:
    name: myminio
    ###
    # The Kubernetes secret name that contains MinIO environment variable configurations.
    # The secret is expected to have a key named config.env containing environment variables exports.
    configuration:
      name: myminio-env-configuration
    ###
    # Root key for dynamically creating a secret for use with configuring root MinIO User
    # Specify the ``name`` and then a list of environment variables.
    #
    # .. important::
    #
    #    Do not use this in production environments.
    #    This field is intended for use with rapid development or testing only.
    #
    # For example:
    #
    # .. code-block:: yaml
    #
    #    name: myminio-env-configuration
    #    accessKey: minio
    #    secretKey: minio123
    #
    configSecret:
      name: myminio-env-configuration
      accessKey: minio
      secretKey: minio123
      #existingSecret: true

    ###
    # If this variable is set to true, then enable the usage of an existing Kubernetes secret to set environment variables for the Tenant.
    # The existing Kubernetes secret name must be placed under .tenant.configuration.name e.g. existing-minio-env-configuration
    # The secret must contain a key ``config.env``.
    # The values should be a series of export statements to set environment variables for the Tenant.
    # For example:
    #
    # .. code-block:: shell
    #
    #    stringData:
    #       config.env: |-
    #         export MINIO_ROOT_USER=ROOTUSERNAME
    #         export MINIO_ROOT_PASSWORD=ROOTUSERPASSWORD
    #
    #   existingSecret: false
    ###
    # Top level key for configuring MinIO Pool(s) in this Tenant.
    #
    # See `Operator CRD: Pools <https://min.io/docs/minio/kubernetes/upstream/reference/operator-crd.html#pool>`__ for more information on all subfields.
    pools:
      ###
      # The number of MinIO Tenant Pods / Servers in this pool.
      # For standalone mode, supply 1. For distributed mode, supply 4 or more.
      # Note that the operator does not support upgrading from standalone to distributed mode.
      - servers: 1
        ###
        # Custom name for the pool
        name: pool-0
        ###
        # The number of volumes attached per MinIO Tenant Pod / Server.
        volumesPerServer: 2
        ###
        # The capacity per volume requested per MinIO Tenant Pod.
        size: 10Gi
  ingress:
    api:
      enabled: false
      ingressClassName: ""
      labels: { }
      annotations: { }
      tls: [ ]
      host: minio.local
      path: /
      pathType: Prefix
    console:
      enabled: false
      ingressClassName: ""
      labels: { }
      annotations: { }
      tls: [ ]
      host: minio-console.local
      path: /
      pathType: Prefix
  # Use an extraResources template section to include additional Kubernetes resources
  # with the Helm deployment.
  #extraResources:
  #  - |
  #    apiVersion: v1
  #    kind: Secret
  #    type: Opaque
  #    metadata:
  #      name: {{ dig "tenant" "configSecret" "name" "" (.Values | merge (dict)) }}
  #    stringData:
  #      config.env: |-
  #        export MINIO_ROOT_USER='minio'
  #        export MINIO_ROOT_PASSWORD='minio123'
