---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .Release.Namespace }}-minio-random-passwd-external-secret"
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  target:
    name: "{{ .Release.Namespace }}-minio-random-password-secret"
    creationPolicy: Owner
    deletionPolicy: Delete
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: "{{ .Release.Namespace }}-minio-random-password-generator"
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: "{{ .Release.Namespace }}-minio-random-password-generator"
  namespace: {{ .Release.Namespace }}
spec:
  length: 12
  digits: 5
  symbols: 5
  symbolCharacters: "$@%$#!&"
  noUpper: false
  allowRepeat: false
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .Release.Namespace }}-minio-external-secret"
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    name: "{{ .Release.Name }}-secret-store"
    kind: SecretStore
  refreshInterval: "1h"
  target:
    name: minio-admin-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        config.env: |-
          export MINIO_ROOT_USER="root"
          export MINIO_ROOT_PASSWORD="{{ `{{ .password }}` }}"
  data:
  - secretKey: password
    remoteRef:
      key: "{{ .Release.Namespace }}-minio-random-password-secret"
      property: password
