apiVersion: v2
name: prometheus-grafana
description: Kube prometheus stack Helm chart configurated by Ujstor
type: application
version: 1.0.0
appVersion: "v0.79.0"

dependencies:
- name: kube-prometheus-stack
  version: 67.2.0
  repository: https://prometheus-community.github.io/helm-charts
  alias: prometheus-grafana
