apiVersion: v2
name: hashicorp-vault
description: Vault Helm chart configured by Ujstor
type: application
version: 1.0.0
appVersion: "1.18.1"

dependencies:
- name: vault
  version: 0.29.0
  repository: https://helm.releases.hashicorp.com
