{{- if and (eq .Values.secretStore.provider.type "kubernetes") .Values.secretStore.provider.kubernetes.auth.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.secretStore.provider.kubernetes.auth.serviceAccount.name | default (include "secret-store.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "secret-store.labels" . | nindent 4 }}
  {{- with .Values.secretStore.provider.kubernetes.auth.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
