apiVersion: v2
name: argo-cd
description: Argo Helm chart configured by Ujstor
type: application
version: 1.0.0
appVersion: "v2.13.0"

dependencies:
- name: argo-cd
  version: 7.7.3
  repository: https://argoproj.github.io/argo-helm
  alias: argo
